### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by JohnTailor** [ajbc/lda-svi#4]
Hi,

Thanks for the code, but it seems to crash :

C:\Python27\python.exe lda-svi-master/onlinewikipedia.py
downloaded 0/64 articles...
downloaded 8/64 articles...
downloaded 16/64 articles...
downloaded 24/64 articles...
downloaded 32/64 articles...
downloaded 40/64 articles...
downloaded 48/64 articles...
downloaded 56/64 articles...
Traceback (most recent call last):
  File "lda-svi-master/onlinewikipedia.py", line 74, in <module>
    main()
  File "lda-svi-master/onlinewikipedia.py", line 58, in main
    (gamma, bound) = olda.update_lambda(docset)
  File "lda-svi-master\onlineldavb.py", line 274, in update_lambda
    bound = self.approx_bound(docs, gamma)
  File "lda-svi-master\onlineldavb.py", line 349, in approx_bound
    score = score * self._D / len(docs)
RuntimeWarning: invalid value encountered in double_scalars

**Comment by zhanwangchen** [comment]
Same here, how did you solved it?

I am using 
Python 2.7.12 :: Anaconda custom (64-bit)

**Comment by JohnTailor** [comment]
I did not solve it. In the end the Gensim library was good enough. My goal was to benchmark my own topic model with LDA ( https://github.com/JohnTailor/tkm )
